name = "koreka"
main = "src/index.ts"
compatibility_date = "2026-03-20"

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "koreka-db"
database_id = "db56f36d-c1f6-4217-854c-424d911fcfcf"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]
