-- 2026年3月 時事ネタ・トレンドカード追加
INSERT OR IGNORE INTO cards (id, text, category, generated) VALUES
-- 時事ネタ (trending) - 2026トレンド
('trd-101', 'ChatGPTに全員のあだ名を考えさせる', 'trending', 0),
('trd-102', 'AIで全員のアイドル風プロフ写真を生成する', 'trending', 0),
('trd-103', 'ブレインロットの推しキャラを語り合う', 'trending', 0),
('trd-104', 'mojojojo vs LABUBUどっち派？ディベート', 'trending', 0),
('trd-105', '全員でPOKÉDANCEを踊ってみる', 'trending', 0),
('trd-106', 'BeRealで今この瞬間を撮ってシェアする', 'trending', 0),
('trd-107', 'ぬい活ごっこ：ぬいぐるみとお出かけ写真', 'trending', 0),
('trd-108', 'シール交換用のシール帳を即席で作る', 'trending', 0),
('trd-109', 'Italian Brainrotのモノマネ大会', 'trending', 0),
('trd-110', 'AIに「今日のグループの運勢」を占わせる', 'trending', 0),
('trd-111', 'ドバイチョコ餅を買いに行く', 'trending', 0),
('trd-112', '麻辣湯を食べに行って辛さチャレンジ', 'trending', 0),
('trd-113', '「好きすぎて滅」ポーズで全員集合写真', 'trending', 0),
('trd-114', '全員のスマホのBeReal履歴を見せ合う', 'trending', 0),
('trd-115', 'Robloxで一緒に遊ぶ', 'trending', 0),
('trd-116', 'HYROXチャレンジ：腕立て腹筋スクワット対決', 'trending', 0),
('trd-117', 'ポケパークの行き方を全員で調べて計画する', 'trending', 0),
('trd-118', 'スマホなし旅行を1時間だけやってみる', 'trending', 0),
('trd-119', 'メロジョイスクイーズを触りに行く', 'trending', 0),
('trd-120', 'KAWAII MONSTER LANDに行ってみる', 'trending', 0),
('trd-121', 'teamLabに行って映え写真を撮りまくる', 'trending', 0),
('trd-122', '都庁ポケモンライトショーを見に行く', 'trending', 0),
('trd-123', 'AIに全員の恋愛相性を診断させる', 'trending', 0),
('trd-124', '推し活プレゼン：自分の推しを3分で布教', 'trending', 0),
('trd-125', 'VTuberの切り抜きを見て全員で実況する', 'trending', 0),
('trd-126', 'たまごっちで対決する', 'trending', 0),
('trd-127', 'ガチャガチャ1000円分引いて戦利品見せ合う', 'trending', 0),
('trd-128', '3Dアイスを食べに行く', 'trending', 0),
('trd-129', '今バズってるリアリティショーを語り合う', 'trending', 0),
('trd-130', 'デコ防犯ブザーを作ってみる', 'trending', 0),
('trd-131', '全員でナルトダンスを踊る', 'trending', 0),
('trd-132', 'せいろ蒸しを食べに行く', 'trending', 0),
('trd-133', 'AIに全員の「推し診断」を作ってもらう', 'trending', 0),
('trd-134', '腸活ドリンクを全員で飲み比べする', 'trending', 0),
('trd-135', 'ChatGPTで即興小説を全員で1文ずつ書く', 'trending', 0),
('trd-136', '日本一高いスタバ（渋谷）に行ってみる', 'trending', 0),
('trd-137', 'ヨアジョン（韓国スイーツ）を食べに行く', 'trending', 0),
('trd-138', '全員でAI画像生成バトル：一番面白い画像勝ち', 'trending', 0),
('trd-139', '「○○で滅」を使って全員のモノマネをする', 'trending', 0),
('trd-140', 'オフラインチャレンジ：SNS断ちで30分過ごす', 'trending', 0);
